/**
 * Botlink tests — offline, localhost only. Proves the whole lane end to end
 * with keys generated by our own pure-TS keygen (if the OpenSSH container or
 * blob encoding is malformed, ssh2's parseKey rejects it HERE, not in
 * production): key parseability, status/inject roundtrips, and every
 * refusal path (wrong key, wrong user, unknown verb, bad payload, host-key
 * mismatch, oversize text).
 *
 * Usage: node --test tests/botlink.test.mjs   (build first: npm run build)
 */

import test from "node:test";
import assert from "node:assert/strict";
import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import ssh2 from "ssh2";
const { Client, utils } = ssh2;
import { generateBotKey, fingerprintOfPublicKey, startBotlinkServer, botlinkRequest, verifyInjectLog, appendInjectEvent, renderInjectReport, buildFileTransfer, sanitizeFileName, BOTLINK_MAX_FILE_BYTES } from "../dist/botlink.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

function tmpDir() {
  return fs.mkdtempSync(path.join(os.tmpdir(), "botlink-test-"));
}

/** Server bound to an ephemeral localhost port + a legit client identity. */
async function makeServer(t, extra = {}) {
  const dir = tmpDir();
  const host = generateBotKey("test-host");
  const clientBot = generateBotKey("client-bot");
  const spool = path.join(dir, "spool");
  const srv = startBotlinkServer({
    listen: { host: "127.0.0.1", port: 0 },
    hostKeyPem: host.privatePem,
    authorizedPublicKeys: [clientBot.publicLine],
    spoolDir: spool,
    botName: "test-machine",
    ...extra,
  });
  await srv.listening;
  t.after(() => srv.close());
  return { srv, host, clientBot, spool };
}

test("keygen: ssh2 parses our keys, private matches its own public line", () => {
  const key = generateBotKey("roundtrip");
  assert.match(key.fingerprint, /^SHA256:[A-Za-z0-9+/]{43}$/);
  assert.ok(key.publicLine.startsWith("ssh-ed25519 "), "public line format");
  assert.ok(key.privatePem.includes("BEGIN OPENSSH PRIVATE KEY"));
  // ssh2 must accept both halves — this is the wire-format proof.
  const parsed = utils.parseKey(key.privatePem);
  assert.ok(parsed, "ssh2 parses our generated private key");
  assert.equal(
    Buffer.from(parsed.getPublicSSH()).toString("base64"),
    key.publicLine.split(" ")[1],
    "private key matches its own public line",
  );
  const parsedPub = utils.parseKey(key.publicLine);
  assert.ok(parsedPub, "ssh2 parses the public line too");
  assert.equal(
    Buffer.from(parsedPub.getPublicSSH()).toString("base64"),
    key.publicLine.split(" ")[1],
  );
});

test("keygen self-verify: EVERY emitted pair is parseable (ssh2 intermittently emits malformed containers)", () => {
  // Upstream bug, measured at ~0.4% (8/2000): generateKeyPairSync("ed25519")
  // occasionally drops a length prefix in the private section — ssh2's parser
  // and ssh-keygen both reject the file. generateBotKey self-verifies and
  // regenerates, so this loop must NEVER see an unparseable key; a failure
  // here means the retry guard itself broke.
  for (let i = 0; i < 300; i++) {
    const key = generateBotKey(`loop-${i}`);
    const priv = utils.parseKey(key.privatePem);
    assert.ok(priv, `iteration ${i}: private PEM must parse`);
    assert.equal(
      Buffer.from(priv.getPublicSSH()).toString("base64"),
      key.publicLine.split(" ")[1],
      `iteration ${i}: private must match its own public line`,
    );
  }
});

test("status/inject roundtrip over localhost", async (t) => {
  const { srv, host, clientBot, spool } = await makeServer(t, { botName: "roundtrip-machine" });
  const peer = {
    host: "127.0.0.1",
    port: srv.port,
    privateKeyPem: clientBot.privatePem,
    expectedHostKey: host.fingerprint,
  };
  const status = JSON.parse(await botlinkRequest(peer, "status"));
  assert.equal(status.ok, true);
  assert.equal(status.bot, "roundtrip-machine");
  assert.equal(status.spool_pending, 0);

  const ack = JSON.parse(
    await botlinkRequest(peer, "inject", {
      source: "client-bot",
      target: "orchestrator",
      text: "health ping from the test suite",
      thread: "shim",
    }),
  );
  assert.ok(ack.ok && ack.id, "inject acked");
  const files = fs.readdirSync(spool).filter((f) => f.endsWith(".inject.json"));
  assert.equal(files.length, 1, "exactly one spool file");
  const saved = JSON.parse(fs.readFileSync(path.join(spool, files[0]), "utf8"));
  assert.equal(saved.source, "client-bot");
  assert.equal(saved.target, "orchestrator");
  assert.equal(saved.text, "health ping from the test suite");
  assert.equal(saved.thread, "shim");
  // Provenance fields: WHICH key authenticated, from WHERE — independent of
  // the sender's self-reported `source`.
  assert.equal(saved.authenticated_key_fp, clientBot.fingerprint, "receiver recorded the authenticating key");
  assert.equal(saved.peer_ip, "127.0.0.1", "receiver recorded the peer address");
  // Audit log: one "received" entry, hash chain intact.
  const log1 = verifyInjectLog(spool);
  assert.equal(log1.length, 1);
  assert.equal(log1[0].event, "received");
  assert.equal(log1[0].id, ack.id);

  const status2 = JSON.parse(await botlinkRequest(peer, "status"));
  assert.equal(status2.injects_total, 1);
  assert.equal(status2.spool_pending, 1);
});

test("wrong client key is refused", async (t) => {
  const { srv, host } = await makeServer(t);
  const imposter = generateBotKey("imposter");
  await assert.rejects(
    botlinkRequest(
      { host: "127.0.0.1", port: srv.port, privateKeyPem: imposter.privatePem, expectedHostKey: host.fingerprint },
      "status",
    ),
    /unreachable|configured authentication|authentication|closed/i,
    "imposter key must not authenticate",
  );
});

test("host-key mismatch is refused (no TOFU)", async (t) => {
  const { srv, clientBot } = await makeServer(t);
  const wrongPin = generateBotKey("not-the-host").fingerprint;
  await assert.rejects(
    botlinkRequest(
      { host: "127.0.0.1", port: srv.port, privateKeyPem: clientBot.privatePem, expectedHostKey: wrongPin },
      "status",
    ),
    /unreachable|Could not connect|handshake|timed? ?out|Bad host key/i,
    "pinned fingerprint mismatch must fail the connection",
  );
});

test("unknown verb and malformed payloads are refused; nothing spools", async (t) => {
  const { srv, host, clientBot, spool } = await makeServer(t);
  const peer = {
    host: "127.0.0.1",
    port: srv.port,
    privateKeyPem: clientBot.privatePem,
    expectedHostKey: host.fingerprint,
  };

  // Raw exec of a forbidden verb through the same transport — the tool layer
  // only ever offers status/inject, so this simulates a hostile peer.
  const forbidden = await new Promise((resolve) => {
    const conn = new Client();
    conn
      .on("ready", () => {
        conn.exec("cat /etc/shadow", (err, stream) => {
          if (err) {
            conn.end();
            return resolve("rejected");
          }
          stream.on("close", (code) => {
            conn.end();
            resolve("ran-exit-" + code);
          });
          stream.end();
        });
      })
      .on("error", () => {
        conn.end();
        resolve("conn-error");
      })
      .connect({
        host: "127.0.0.1",
        port: srv.port,
        username: "clanker",
        privateKey: clientBot.privatePem,
        hostVerifier: (key) => key.toString("base64") === host.publicLine.split(" ")[1],
      });
  });
  assert.notEqual(forbidden, "ran-exit-0", "arbitrary commands must not run");
  assert.equal(fs.readdirSync(spool).filter((f) => f.endsWith(".inject.json")).length, 0, "nothing spooled by refusal");

  // Port forwarding must be refused — the lane is verbs-only, not a tunnel.
  const fwd = await new Promise((resolve) => {
    const conn = new Client();
    conn
      .on("ready", () => {
        conn.forwardOut("127.0.0.1", 0, "127.0.0.1", 22, (err, stream) => {
          conn.end();
          if (err) return resolve("refused");
          stream.close();
          return resolve("forwarded");
        });
      })
      .on("error", () => {
        conn.end();
        resolve("refused");
      })
      .connect({
        host: "127.0.0.1",
        port: srv.port,
        username: "clanker",
        privateKey: clientBot.privatePem,
        hostVerifier: (key) => key.toString("base64") === host.publicLine.split(" ")[1],
      });
  });
  assert.equal(fwd, "refused", "direct-tcpip forwarding must not be honored");

  // Oversized text.
  await assert.rejects(
    botlinkRequest(peer, "inject", { source: "c", target: "x", text: "x".repeat(4001) }),
    /invalid payload/i,
  );
  // Missing target.
  await assert.rejects(botlinkRequest(peer, "inject", { source: "c", text: "hi" }), /invalid payload/i);
  assert.equal(fs.readdirSync(spool).filter((f) => f.endsWith(".inject.json")).length, 0, "still nothing spooled");
});

test("inject audit log is tamper-evident: edits and deletions are caught", async (t) => {
  const { srv, host, clientBot, spool } = await makeServer(t);
  const peer = {
    host: "127.0.0.1",
    port: srv.port,
    privateKeyPem: clientBot.privatePem,
    expectedHostKey: host.fingerprint,
  };
  await botlinkRequest(peer, "inject", { source: "a", target: "b", text: "one" });
  await botlinkRequest(peer, "inject", { source: "c", target: "d", text: "two" });
  assert.equal(verifyInjectLog(spool).length, 2, "both received entries chain cleanly");

  // Tamper with an entry's text field → chain verify must fail.
  const logPath = path.join(spool, "inject.log");
  const lines = fs.readFileSync(logPath, "utf8").split("\n").filter(Boolean);
  const doctored = JSON.parse(lines[0]);
  doctored.detail = "innocent entry, honest";
  lines[0] = JSON.stringify(doctored);
  fs.writeFileSync(logPath, lines.join("\n") + "\n");
  assert.throws(() => verifyInjectLog(spool), /chain broken/, "edited entry detected");

  // Delete the FIRST entry → second entry's prev link no longer matches genesis.
  const lines2 = fs.readFileSync(logPath, "utf8").split("\n").filter(Boolean);
  fs.writeFileSync(logPath, lines2.slice(1).join("\n") + "\n");
  assert.throws(() => verifyInjectLog(spool), /chain/, "removed entry detected");
});

test("concurrent injects serialize into an intact chain (interleaved-writer race)", async (t) => {
  const { srv, host, clientBot, spool } = await makeServer(t);
  const peer = {
    host: "127.0.0.1",
    port: srv.port,
    privateKeyPem: clientBot.privatePem,
    expectedHostKey: host.fingerprint,
  };
  const N = 8;
  await Promise.all(
    Array.from({ length: N }, (_, i) =>
      botlinkRequest(peer, "inject", { source: `s${i}`, target: `t${i}`, text: `burst ${i}` }).catch((e) => {
        throw new Error(`inject ${i} failed: ${e.message}`);
      }),
    ),
  );
  const entries = verifyInjectLog(spool); // throws if the chain interleaved/broke
  assert.equal(entries.length, N, `all ${N} received entries present, chain verifies`);
  const ids = new Set(entries.map((e) => e.id));
  assert.equal(ids.size, N, "no duplicate ids");
});

test("structured task payloads roundtrip; junk task fields are refused", async (t) => {
  const { srv, host, clientBot, spool } = await makeServer(t);
  const peer = {
    host: "127.0.0.1",
    port: srv.port,
    privateKeyPem: clientBot.privatePem,
    expectedHostKey: host.fingerprint,
  };
  const ack = JSON.parse(
    await botlinkRequest(peer, "inject", {
      source: "client-bot",
      target: "shim",
      text: "review the re-vendor branch",
      thread: "shim",
      task: {
        kind: "review",
        repo: "shim",
        branch: "main",
        commit: "58833e6",
        acceptance: ["drift gate clean", "host_tests 570/570"],
        reply_to: "1790904000000-abc123",
        correlation: "round-7",
      },
      supersedes: "1790903000000-old456",
    }),
  );
  assert.ok(ack.ok);
  const files = fs.readdirSync(spool).filter((f) => f.endsWith(".inject.json"));
  const saved = JSON.parse(fs.readFileSync(path.join(spool, files[0]), "utf8"));
  assert.equal(saved.task.kind, "review");
  assert.equal(saved.task.commit, "58833e6");
  assert.deepEqual(saved.task.acceptance, ["drift gate clean", "host_tests 570/570"]);
  assert.equal(saved.task.reply_to, "1790904000000-abc123");
  // lineage fields survive zod — reserved so peers can adopt them without a
  // breaking schema change (unknown keys would otherwise be silently stripped)
  assert.equal(saved.task.correlation, "round-7");
  assert.equal(saved.supersedes, "1790903000000-old456");
  // audit detail carries kind + reply_to + lineage for metrics derivation
  const log = verifyInjectLog(spool);
  assert.match(log[0].detail ?? "", /kind=review/);
  assert.match(log[0].detail ?? "", /reply_to=1790904000000-abc123/);
  assert.match(log[0].detail ?? "", /supersedes=1790903000000-old456/);
  assert.match(log[0].detail ?? "", /correlation=round-7/);

  // junk kind / oversize acceptance / unknown field → refused, nothing spooled
  await assert.rejects(
    botlinkRequest(peer, "inject", { source: "c", target: "x", text: "hi", task: { kind: "destroy" } }),
    /invalid payload/i,
  );
  await assert.rejects(
    botlinkRequest(peer, "inject", {
      source: "c", target: "x", text: "hi",
      task: { kind: "review", acceptance: ["x".repeat(401)] },
    }),
    /invalid payload/i,
  );
  assert.equal(fs.readdirSync(spool).filter((f) => f.endsWith(".inject.json")).length, 1, "only the valid inject spooled");
});

test("report: metrics derive from the audit log (latency, completed, rework)", async (t) => {
  const { srv, host, clientBot, spool } = await makeServer(t);
  const peer = {
    host: "127.0.0.1",
    port: srv.port,
    privateKeyPem: clientBot.privatePem,
    expectedHostKey: host.fingerprint,
  };
  const first = JSON.parse(
    await botlinkRequest(peer, "inject", { source: "a", target: "shim", text: "one", task: { kind: "implement", reply_to: "R1" } }),
  );
  await new Promise((r) => setTimeout(r, 50));
  const second = JSON.parse(
    await botlinkRequest(peer, "inject", { source: "a", target: "shim", text: "two", task: { kind: "review", reply_to: "R1" } }),
  );
  // receiver-side lifecycle event on the first
  await appendInjectEvent(spool, { event: "completed", id: first.id, source: "a", target: "shim", detail: "merged @ aaa5592" });
  await appendInjectEvent(spool, { event: "consumed", id: first.id, source: "a", target: "shim" });
  const report = renderInjectReport(spool);
  assert.match(report, /2 inject\(s\), chain verified/);
  assert.match(report, /completed lifecycle events: 1/);
  assert.match(report, /merged @ aaa5592/);
  assert.match(report, /rework rounds \(shared reply_to\): 1/);
  assert.match(report, /received→consumed latency: \d+ms median \(1 paired\)/);
  assert.ok(second.ok);
});

test("append queue survives a failed append — audit trail never freezes (their reviewer's catch)", async (t) => {
  const { spool } = await makeServer(t);
  const logPath = path.join(spool, "inject.log");
  fs.writeFileSync(logPath, ""); // genesis — exists, so only the APPEND can fail
  // Make the append fail once: read-only log (deterministic EACCES as non-root
  // — same class as their reviewer's EBUSY/ENOSPC on Windows AV locks).
  fs.chmodSync(logPath, 0o444);
  t.after(() => fs.chmodSync(logPath, 0o644));
  const first = await appendInjectEvent(spool, { event: "received", id: "a1", source: "s", target: "t" }).then(
    () => "ok",
    () => "failed",
  );
  assert.equal(first, "failed", "first append hits the read-only log");
  fs.chmodSync(logPath, 0o644);
  const second = await appendInjectEvent(spool, { event: "received", id: "a2", source: "s", target: "t" }).then(
    () => "ok",
    () => "failed",
  );
  assert.equal(second, "ok", "queue recovered — the failure did not poison later appends");
  const entries = verifyInjectLog(spool);
  assert.equal(entries.length, 1, "only the recovered entry landed");
  assert.equal(entries[0].id, "a2");
});

test("report reconciles archive files against the log — a lost append is visible", async (t) => {
  const { srv, host, clientBot, spool } = await makeServer(t);
  const peer = {
    host: "127.0.0.1",
    port: srv.port,
    privateKeyPem: clientBot.privatePem,
    expectedHostKey: host.fingerprint,
  };
  // One clean inject (file + received event + consumed + archive move).
  const ack = JSON.parse(
    await botlinkRequest(peer, "inject", { source: "a", target: "shim", text: "logged one", task: { kind: "status" } }),
  );
  assert.ok(ack.ok);
  await new Promise((r) => setTimeout(r, 150));
  fs.mkdirSync(path.join(spool, "archive"), { recursive: true });
  fs.renameSync(
    path.join(spool, `${ack.id}.inject.json`),
    path.join(spool, "archive", `${ack.id}.inject.json`),
  );
  // Now forge the failure signature: a file lands in archive whose received
  // entry never made the log (simulates append-loss AFTER the spool write).
  fs.writeFileSync(path.join(spool, "archive", "9999000000-dead00.inject.json"), '{"id":"9999000000-dead00"}');
  const report = renderInjectReport(spool);
  assert.match(report, /unlogged inject files \(audit append lost\): 1/);
  assert.match(report, /9999000000-dead00/);
  // and the clean case shows no false positive for the logged one
  assert.doesNotMatch(report, new RegExp(`unlogged[^\n]*${ack.id}`));
});

test("tail truncation is caught by the head artifact; legacy headless logs still verify", async (t) => {
  const { spool } = await makeServer(t);
  const logPath = path.join(spool, "inject.log");
  await appendInjectEvent(spool, { event: "received", id: "t1", source: "s", target: "t" });
  await appendInjectEvent(spool, { event: "consumed", id: "t1", source: "s", target: "t" });
  assert.equal(verifyInjectLog(spool).length, 2, "both entries chain-verify");

  // Delete the NEWEST line: replay alone sees a valid shorter chain — the
  // persisted head hash is what catches it (their reviewer's part-2 catch).
  const lines = fs.readFileSync(logPath, "utf8").split("\n").filter(Boolean);
  fs.writeFileSync(logPath, lines.slice(0, -1).join("\n") + "\n");
  assert.throws(() => verifyInjectLog(spool), /tail truncated/, "newest-entry deletion detected");

  // Legacy log with no .head artifact: replay verdict stands (can't tell
  // "never written" from "deleted" — fail-open on the artifact, never invent).
  fs.rmSync(path.join(spool, "inject.log.head"));
  assert.equal(verifyInjectLog(spool).length, 1, "legacy headless log still verifies");
});

test("log entries carry structured lineage meta; rework derives from the field, not detail text", async (t) => {
  const { srv, host, clientBot, spool } = await makeServer(t);
  const peer = {
    host: "127.0.0.1",
    port: srv.port,
    privateKeyPem: clientBot.privatePem,
    expectedHostKey: host.fingerprint,
  };
  await botlinkRequest(peer, "inject", { source: "a", target: "shim", text: "one", task: { kind: "implement", reply_to: "R9" } });
  await botlinkRequest(peer, "inject", { source: "a", target: "shim", text: "two", task: { kind: "review", reply_to: "R9" } });
  const entries = verifyInjectLog(spool);
  const withMeta = entries.filter((e) => e.meta?.reply_to === "R9");
  assert.equal(withMeta.length, 2, "both received entries carry meta.reply_to (hash-covered)");
  // even with detail text gone, rework still derives — no format-drift zeroing
  const report = renderInjectReport(spool);
  assert.match(report, /rework rounds \(shared reply_to\): 1/);
});

test("fingerprintOfPublicKey accepts blobs and lines; rejects junk", () => {
  const key = generateBotKey("fp");
  assert.equal(fingerprintOfPublicKey(key.publicLine), key.fingerprint);
  assert.equal(fingerprintOfPublicKey(key.publicLine.split(" ")[1]), key.fingerprint);
  assert.throws(() => fingerprintOfPublicKey("not a key"), /not a public key/);
});

test("spool-depth cap: inject past maxSpoolPending is refused, nothing spooled (disk-fill guard)", async (t) => {
  const { srv, host, clientBot, spool } = await makeServer(t, { maxSpoolPending: 1 });
  const peer = {
    host: "127.0.0.1",
    port: srv.port,
    privateKeyPem: clientBot.privatePem,
    expectedHostKey: host.fingerprint,
  };
  const first = JSON.parse(await botlinkRequest(peer, "inject", { source: "a", target: "shim", text: "one" }));
  assert.ok(first.ok, "first inject spools (cap not yet reached)");
  // Nothing consumes the spool in this test — the second inject must hit the cap.
  await assert.rejects(
    botlinkRequest(peer, "inject", { source: "a", target: "shim", text: "two" }),
    /spool full/i,
    "inject past the pending cap is refused with a clear reason",
  );
  assert.equal(fs.readdirSync(spool).filter((f) => f.endsWith(".inject.json")).length, 1, "refused inject wrote no file");
  // Status still answers and reports the honest depth.
  const status = JSON.parse(await botlinkRequest(peer, "status"));
  assert.equal(status.spool_pending, 1);
  assert.equal(status.injects_total, 1, "refused inject is not counted");
});

test("connection cap: beyond maxConnections the SSH handshake is dropped (slowloris guard)", async (t) => {
  const { srv, host, clientBot } = await makeServer(t, { maxConnections: 1 });
  const connect = () => {
    const conn = new Client();
    const ready = new Promise((resolve, reject) => {
      conn.on("ready", () => resolve(conn));
      conn.on("error", reject);
      // A server that drops the connection mid-handshake (the cap path) can
      // emit ONLY 'close' — without this listener the promise never settles
      // (the exact hang the library client fix covers; raw clients need it too).
      conn.on("close", () => reject(new Error("connection closed before ready")));
      conn.connect({
        host: "127.0.0.1",
        port: srv.port,
        username: "clanker",
        privateKey: clientBot.privatePem,
        hostVerifier: (key) => key.toString("base64") === host.publicLine.split(" ")[1],
      });
    });
    return { conn, ready };
  };
  const held = connect();
  t.after(() => held.conn.end());
  await held.ready; // connection #1 authenticated and parked (no exec, no data)
  // Connection #2 must be refused at the door — the server has no free slot.
  const second = connect();
  const outcome = await Promise.race([
    second.ready.then(
      () => "admitted",
      () => "refused", // error OR close-only — both are refusals (see connect())
    ),
    new Promise((resolve) => setTimeout(() => resolve("timeout"), 3000)),
  ]);
  second.conn.end();
  assert.notEqual(outcome, "admitted", "a parked connection must block new ones past the cap");
  assert.notEqual(outcome, "timeout", "the refusal must be immediate-ish, not silence");
  // After the held connection goes away, a fresh one gets in again.
  held.conn.end();
  await new Promise((r) => setTimeout(r, 150));
  const third = connect();
  await third.ready;
  third.conn.end();
});

test("client never hangs: a peer that closes mid-handshake rejects, close-only (no error event)", async () => {
  // Regression for the connection-cap discovery: refused/dying connections can
  // surface as a bare socket 'close' — the request must settle, not pend.
  const net = await import("node:net");
  const dropper = net.createServer((socket) => socket.destroy()); // accept, then RST-ish close
  await new Promise((resolve) => dropper.listen(0, "127.0.0.1", resolve));
  const port = dropper.address().port;
  const anyKey = generateBotKey("hang-probe");
  await assert.rejects(
    botlinkRequest(
      { host: "127.0.0.1", port, privateKeyPem: anyKey.privatePem, expectedHostKey: anyKey.fingerprint },
      "status",
    ),
    /unreachable|closed|timed out|reset/i,
    "connection dropped before handshake must reject within the deadline, never hang",
  );
  dropper.close();
});

test("exec watchdog: an exec channel that never ends is dropped (idle-channel guard)", async (t) => {
  const { srv, host, clientBot } = await makeServer(t, { execTimeoutMs: 150 });
  const verdict = await new Promise((resolve) => {
    const conn = new Client();
    let settled = false;
    const done = (how) => {
      if (!settled) {
        settled = true;
        conn.end();
        resolve(how);
      }
    };
    conn
      .on("ready", () => {
        conn.exec("inject", (err, stream) => {
          if (err) return done("exec-rejected");
          // Hostile shape: open the channel, send a partial payload, never EOF.
          stream.stdin.write('{"source":"a"');
          stream.on("close", () => done("dropped"));
          conn.on("close", () => done("dropped"));
        });
      })
      .on("error", () => done("dropped"))
      .connect({
        host: "127.0.0.1",
        port: srv.port,
        username: "clanker",
        privateKey: clientBot.privatePem,
        hostVerifier: (key) => key.toString("base64") === host.publicLine.split(" ")[1],
      });
    // If the watchdog is broken the channel lives forever — fail, don't hang.
    setTimeout(() => done("still-open"), 3000).unref();
  });
  assert.equal(verdict, "dropped", "stalled exec channel must be closed by the server");
});

// --- file transfer (payload.file / bot_file) ---------------------------------
// Files cross machines on the lane, never Discord. Sender picks a NAME only;
// the receiver sanitizes it and stores under files/<inject-id>/ — plus size,
// sha256, and leak-shape checks at BOTH ends (each end owns its boundary).

test("sanitizeFileName: traversal and junk collapse to harmless basenames", () => {
  assert.equal(sanitizeFileName("../../etc/passwd"), "passwd");
  assert.equal(sanitizeFileName("with/slash.txt"), "slash.txt");
  assert.equal(sanitizeFileName("...hidden"), "_hidden");
  assert.equal(sanitizeFileName(""), "file");
  assert.equal(sanitizeFileName("ctl\x00\x1fname"), "ctlname");
  assert.equal(sanitizeFileName("a".repeat(400)).length, 120);
  // Windows-style separators are not path separators on POSIX basename() —
  // the character replace must still neutralize them.
  const evil = sanitizeFileName("..\\..\\evil.sh");
  assert.ok(!/[\\/]/.test(evil) && !evil.startsWith("."), `windows-style traversal collapsed: "${evil}"`);
});

test("buildFileTransfer: verified payload out; empty/oversize/leak-shaped refused", () => {
  const bytes = Buffer.from("patch content — line 1\nline 2\n");
  const built = buildFileTransfer({ source: "sender-bot", target: "orchestrator", name: "p.txt", bytes });
  if (!("payload" in built)) assert.fail(`clean file refused: ${built.error}`);
  assert.equal(built.payload.file.size, bytes.length);
  assert.equal(built.payload.file.sha256, crypto.createHash("sha256").update(bytes).digest("hex"));
  assert.match(built.payload.text, /^file transfer: p\.txt \(\d+ bytes, sha256 /);

  assert.match(
    buildFileTransfer({ source: "a", target: "o", name: "x", bytes: Buffer.alloc(0) }).error,
    /empty/,
  );
  assert.match(
    buildFileTransfer({ source: "a", target: "o", name: "big.bin", bytes: Buffer.alloc(BOTLINK_MAX_FILE_BYTES + 1, 7) }).error,
    /too large/,
  );
  // The leak tripwire applies to FILE content, not just captions — a file
  // carrying a live token shape is an exfil attempt regardless of framing.
  const leaky = buildFileTransfer({
    source: "a",
    target: "o",
    name: "env.txt",
    bytes: Buffer.from(`DISCORD_TOKEN=${"x".repeat(48)}\n`),
  });
  if (!("error" in leaky)) assert.fail("leak-shaped file passed the builder");
  assert.match(leaky.error, /^REFUSED:/);
});

test("file inject: e2e roundtrip (manifest-only spool, byte-identical landing, audit detail); server refuses tamper/leak/oversize", async (t) => {
  const { srv, host, clientBot, spool } = await makeServer(t);
  const peer = { host: "127.0.0.1", port: srv.port, privateKeyPem: clientBot.privatePem, expectedHostKey: host.fingerprint };

  const bytes = Buffer.from("the quick brown file\n".repeat(24));
  const built = buildFileTransfer({ source: "client-bot", target: "orchestrator", name: "notes.txt", bytes, note: "e2e proof" });
  if (!("payload" in built)) assert.fail(`builder refused a clean file: ${built.error}`);
  const ack = JSON.parse(await botlinkRequest(peer, "inject", built.payload));
  assert.ok(ack.ok && ack.id, "file inject acked");

  const spoolJsons = fs.readdirSync(spool).filter((f) => f.endsWith(".inject.json"));
  assert.equal(spoolJsons.length, 1, "exactly one spool file");
  const saved = JSON.parse(fs.readFileSync(path.join(spool, spoolJsons[0]), "utf8"));
  assert.equal(saved.file.name, "notes.txt");
  assert.equal(saved.file.size, bytes.length);
  assert.ok(!JSON.stringify(saved).includes("content_b64"), "base64 never persists in the spool json");
  assert.match(saved.file.path, /^files\/[^/]+\/notes\.txt$/);
  assert.ok(fs.readFileSync(path.join(spool, saved.file.path)).equals(bytes), "byte-identical roundtrip");
  const entries = verifyInjectLog(spool);
  assert.match(entries[0].detail ?? "", /file notes\.txt \d+B sha256:/);
  assert.match(renderInjectReport(spool), /chain verified/);

  // Server-side refusal 1: sha256 lie (hostile peer skips the builder).
  const wrongSha = crypto.createHash("sha256").update("different bytes").digest("hex");
  await assert.rejects(
    botlinkRequest(peer, "inject", {
      source: "client-bot",
      target: "orchestrator",
      text: "tampered file transfer",
      file: { name: "evil.bin", size: bytes.length, sha256: wrongSha, content_b64: bytes.toString("base64") },
    }),
    /hash mismatch/i,
  );
  // Server-side refusal 2: leak-shaped file content.
  const leakBytes = Buffer.from(`ghp_${"a".repeat(36)}`);
  await assert.rejects(
    botlinkRequest(peer, "inject", {
      source: "client-bot",
      target: "orchestrator",
      text: "leaky file transfer",
      file: {
        name: "tok.txt",
        size: leakBytes.length,
        sha256: crypto.createHash("sha256").update(leakBytes).digest("hex"),
        content_b64: leakBytes.toString("base64"),
      },
    }),
    /REFUSED/,
  );
  // Server-side refusal 3: oversize claim — refused before any decode/write.
  await assert.rejects(
    botlinkRequest(peer, "inject", {
      source: "client-bot",
      target: "orchestrator",
      text: "oversize file transfer",
      file: { name: "huge.bin", size: BOTLINK_MAX_FILE_BYTES + 1, sha256: "0".repeat(64), content_b64: "AAAA" },
    }),
    /too large/i,
  );
  assert.equal(
    fs.readdirSync(spool).filter((f) => f.endsWith(".inject.json")).length,
    1,
    "every refusal spooled nothing",
  );
});

test("file inject: hostile sender-supplied name is collapsed server-side (no traversal)", async (t) => {
  const { srv, host, clientBot, spool } = await makeServer(t);
  const peer = { host: "127.0.0.1", port: srv.port, privateKeyPem: clientBot.privatePem, expectedHostKey: host.fingerprint };
  const bytes = Buffer.from("traversal probe");
  const ack = JSON.parse(
    await botlinkRequest(peer, "inject", {
      source: "client-bot",
      target: "orchestrator",
      text: "raw file with a hostile name",
      file: {
        name: "../../../evil.sh",
        size: bytes.length,
        sha256: crypto.createHash("sha256").update(bytes).digest("hex"),
        content_b64: bytes.toString("base64"),
      },
    }),
  );
  assert.ok(ack.ok, "valid file accepted");
  // Landed strictly inside spool/files/<id>/ with the name collapsed —
  // nowhere outside the spool, no separators left in the name.
  const destDir = path.join(spool, "files", ack.id);
  assert.deepEqual(fs.readdirSync(destDir), ["evil.sh"]);
  assert.ok(fs.readFileSync(path.join(destDir, "evil.sh")).equals(bytes));
  assert.equal(fs.existsSync(path.join(spool, "..", "evil.sh")), false, "nothing escaped the spool");
});

test("file inject hardening: schema bounds the blob, raw accumulator cap refuses pre-parse", async (t) => {
  // Schema-level: content_b64 beyond base64-of-2MB is rejected at PARSE —
  // a hostile peer's oversized blob never reaches the decoder.
  const bytes = Buffer.from("x");
  const bloated = {
    source: "client-bot",
    target: "orchestrator",
    text: "schema-bound probe",
    file: {
      name: "blob.bin",
      size: 1,
      sha256: crypto.createHash("sha256").update(bytes).digest("hex"),
      content_b64: "A".repeat(Math.ceil(BOTLINK_MAX_FILE_BYTES / 3) * 4 + 1),
    },
  };
  const { srv, host, clientBot, spool } = await makeServer(t);
  const peer = { host: "127.0.0.1", port: srv.port, privateKeyPem: clientBot.privatePem, expectedHostKey: host.fingerprint };
  await assert.rejects(botlinkRequest(peer, "inject", bloated), /invalid payload/i);

  // Accumulator cap: raw stdin beyond maxRawPayloadBytes is refused BEFORE
  // parsing — junk that isn't even JSON gets the same wall. Tiny cap here so
  // the test moves bytes, not tens of megabytes.
  const { srv: srv2, host: host2, clientBot: clientBot2, spool: spool2 } = await makeServer(t, { maxRawPayloadBytes: 1024 });
  const peer2 = { host: "127.0.0.1", port: srv2.port, privateKeyPem: clientBot2.privatePem, expectedHostKey: host2.fingerprint };
  await assert.rejects(
    botlinkRequestRaw(peer2, "x".repeat(4096)),
    /payload too large/i,
  );
  assert.equal(
    fs.readdirSync(spool).filter((f) => f.endsWith(".inject.json")).length +
      fs.readdirSync(spool2).filter((f) => f.endsWith(".inject.json")).length,
    0,
    "nothing spooled by either refusal",
  );
});

/** Raw-stdin inject: ship arbitrary bytes as the "payload" (no builder, no
 *  valid JSON) — what a hostile authed peer actually controls. */
function botlinkRequestRaw(peer, raw) {
  // Reuse the public client but intercept the payload write: botlinkRequest
  // only injects JSON for `inject` when given a payload object; without one
  // it sends nothing. So drive ssh2 directly here.
  return new Promise((resolve, reject) => {
    const { Client } = ssh2;
    const conn = new Client();
    const done = (fn) => {
      clearTimeout(timer);
      fn();
    };
    const timer = setTimeout(() => {
      conn.end();
      reject(new Error("raw probe timed out"));
    }, 15_000);
    conn
      .on("ready", () => {
        conn.exec("inject", (err, stream) => {
          if (err) return done(() => reject(err));
          let errOut = "";
          let exitCode = null;
          stream.on("data", () => {}); // drain: without a reader the channel window stalls and 'close' never fires
          stream.stderr.on("data", (c) => (errOut += c.toString()));
          stream.on("exit", (code) => (exitCode = code));
          stream.on("close", () => {
            conn.end();
            done(() =>
              exitCode === 0
                ? resolve("unexpected ok")
                : reject(new Error(errOut.trim() || `exit ${exitCode}`)),
            );
          });
          stream.end(raw);
        });
      })
      .on("error", (err) => done(() => reject(err)))
      .on("close", () => done(() => reject(new Error("closed early"))))
      .connect({
        host: peer.host,
        port: peer.port,
        username: "clanker",
        privateKey: peer.privateKeyPem,
        hostVerifier: (key) => fingerprintOfPublicKey(key.toString("base64")) === peer.expectedHostKey,
        readyTimeout: 10_000,
      });
  });
}

test("status surfaces watcher load while fresh, omits it when absent or stale", async (t) => {
  const { srv, host, clientBot, spool } = await makeServer(t, { botName: "load-machine" });
  const peer = {
    host: "127.0.0.1",
    port: srv.port,
    privateKeyPem: clientBot.privatePem,
    expectedHostKey: host.fingerprint,
  };
  // No watcher-state.json yet → no load key at all.
  const bare = JSON.parse(await botlinkRequest(peer, "status"));
  assert.equal(bare.ok, true);
  assert.equal(bare.load, undefined, "absent watcher-state.json must not add a load key");
  // Fresh state → served verbatim.
  fs.writeFileSync(
    path.join(spool, "watcher-state.json"),
    JSON.stringify({ active: 1, queued_human: 0, queued_bot: 2, updated: new Date().toISOString() }) + "\n",
  );
  const withLoad = JSON.parse(await botlinkRequest(peer, "status"));
  assert.equal(withLoad.load.active, 1);
  assert.equal(withLoad.load.queued_bot, 2);
  // Stale state (beyond the 180s freshness window — the watcher refreshes
  // every 120s, so anything older than 3min means the writer stopped) →
  // omitted, not served as truth.
  fs.writeFileSync(
    path.join(spool, "watcher-state.json"),
    JSON.stringify({ active: 0, updated: new Date(Date.now() - 240_000).toISOString() }) + "\n",
  );
  const stale = JSON.parse(await botlinkRequest(peer, "status"));
  assert.equal(stale.load, undefined, "stale watcher-state.json must be omitted");
});
