/**
 * Botlink tests — offline, localhost only. Proves the whole lane end to end
 * with keys generated by our own pure-TS keygen (if the OpenSSH container or
 * blob encoding is malformed, ssh2's parseKey rejects it HERE, not in
 * production): key parseability, status/inject roundtrips, and every
 * refusal path (wrong key, wrong user, unknown verb, bad payload, host-key
 * mismatch, oversize text).
 *
 * Usage: node --test tests/botlink.test.mjs   (build first: npm run build)
 */

import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import ssh2 from "ssh2";
const { Client, utils } = ssh2;
import { generateBotKey, fingerprintOfPublicKey, startBotlinkServer, botlinkRequest } from "../dist/botlink.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

function tmpDir() {
  return fs.mkdtempSync(path.join(os.tmpdir(), "botlink-test-"));
}

/** Server bound to an ephemeral localhost port + a legit client identity. */
async function makeServer(t, extra = {}) {
  const dir = tmpDir();
  const host = generateBotKey("test-host");
  const clientBot = generateBotKey("client-bot");
  const spool = path.join(dir, "spool");
  const srv = startBotlinkServer({
    listen: { host: "127.0.0.1", port: 0 },
    hostKeyPem: host.privatePem,
    authorizedPublicKeys: [clientBot.publicLine],
    spoolDir: spool,
    botName: "test-machine",
    ...extra,
  });
  await srv.listening;
  t.after(() => srv.close());
  return { srv, host, clientBot, spool };
}

test("keygen: ssh2 parses our keys, private matches its own public line", () => {
  const key = generateBotKey("roundtrip");
  assert.match(key.fingerprint, /^SHA256:[A-Za-z0-9+/]{43}$/);
  assert.ok(key.publicLine.startsWith("ssh-ed25519 "), "public line format");
  assert.ok(key.privatePem.includes("BEGIN OPENSSH PRIVATE KEY"));
  // ssh2 must accept both halves — this is the wire-format proof.
  const parsed = utils.parseKey(key.privatePem);
  assert.ok(parsed, "ssh2 parses our generated private key");
  assert.equal(
    Buffer.from(parsed.getPublicSSH()).toString("base64"),
    key.publicLine.split(" ")[1],
    "private key matches its own public line",
  );
  const parsedPub = utils.parseKey(key.publicLine);
  assert.ok(parsedPub, "ssh2 parses the public line too");
  assert.equal(
    Buffer.from(parsedPub.getPublicSSH()).toString("base64"),
    key.publicLine.split(" ")[1],
  );
});

test("status/inject roundtrip over localhost", async (t) => {
  const { srv, host, clientBot, spool } = await makeServer(t, { botName: "roundtrip-machine" });
  const peer = {
    host: "127.0.0.1",
    port: srv.port,
    privateKeyPem: clientBot.privatePem,
    expectedHostKey: host.fingerprint,
  };
  const status = JSON.parse(await botlinkRequest(peer, "status"));
  assert.equal(status.ok, true);
  assert.equal(status.bot, "roundtrip-machine");
  assert.equal(status.spool_pending, 0);

  const ack = JSON.parse(
    await botlinkRequest(peer, "inject", {
      source: "client-bot",
      target: "orchestrator",
      text: "health ping from the test suite",
      thread: "shim",
    }),
  );
  assert.ok(ack.ok && ack.id, "inject acked");
  const files = fs.readdirSync(spool).filter((f) => f.endsWith(".inject.json"));
  assert.equal(files.length, 1, "exactly one spool file");
  const saved = JSON.parse(fs.readFileSync(path.join(spool, files[0]), "utf8"));
  assert.equal(saved.source, "client-bot");
  assert.equal(saved.target, "orchestrator");
  assert.equal(saved.text, "health ping from the test suite");
  assert.equal(saved.thread, "shim");

  const status2 = JSON.parse(await botlinkRequest(peer, "status"));
  assert.equal(status2.injects_total, 1);
  assert.equal(status2.spool_pending, 1);
});

test("wrong client key is refused", async (t) => {
  const { srv, host } = await makeServer(t);
  const imposter = generateBotKey("imposter");
  await assert.rejects(
    botlinkRequest(
      { host: "127.0.0.1", port: srv.port, privateKeyPem: imposter.privatePem, expectedHostKey: host.fingerprint },
      "status",
    ),
    /unreachable|configured authentication|authentication|closed/i,
    "imposter key must not authenticate",
  );
});

test("host-key mismatch is refused (no TOFU)", async (t) => {
  const { srv, clientBot } = await makeServer(t);
  const wrongPin = generateBotKey("not-the-host").fingerprint;
  await assert.rejects(
    botlinkRequest(
      { host: "127.0.0.1", port: srv.port, privateKeyPem: clientBot.privatePem, expectedHostKey: wrongPin },
      "status",
    ),
    /unreachable|Could not connect|handshake|timed? ?out|Bad host key/i,
    "pinned fingerprint mismatch must fail the connection",
  );
});

test("unknown verb and malformed payloads are refused; nothing spools", async (t) => {
  const { srv, host, clientBot, spool } = await makeServer(t);
  const peer = {
    host: "127.0.0.1",
    port: srv.port,
    privateKeyPem: clientBot.privatePem,
    expectedHostKey: host.fingerprint,
  };

  // Raw exec of a forbidden verb through the same transport — the tool layer
  // only ever offers status/inject, so this simulates a hostile peer.
  const forbidden = await new Promise((resolve) => {
    const conn = new Client();
    conn
      .on("ready", () => {
        conn.exec("cat /etc/shadow", (err, stream) => {
          if (err) {
            conn.end();
            return resolve("rejected");
          }
          stream.on("close", (code) => {
            conn.end();
            resolve("ran-exit-" + code);
          });
          stream.end();
        });
      })
      .on("error", () => {
        conn.end();
        resolve("conn-error");
      })
      .connect({
        host: "127.0.0.1",
        port: srv.port,
        username: "clanker",
        privateKey: clientBot.privatePem,
        hostVerifier: (key) => key.toString("base64") === host.publicLine.split(" ")[1],
      });
  });
  assert.notEqual(forbidden, "ran-exit-0", "arbitrary commands must not run");
  assert.equal(fs.readdirSync(spool).length, 0, "nothing spooled by refusal");

  // Oversized text.
  await assert.rejects(
    botlinkRequest(peer, "inject", { source: "c", target: "x", text: "x".repeat(4001) }),
    /invalid payload/i,
  );
  // Missing target.
  await assert.rejects(botlinkRequest(peer, "inject", { source: "c", text: "hi" }), /invalid payload/i);
  assert.equal(fs.readdirSync(spool).length, 0, "still nothing spooled");
});

test("fingerprintOfPublicKey accepts blobs and lines; rejects junk", () => {
  const key = generateBotKey("fp");
  assert.equal(fingerprintOfPublicKey(key.publicLine), key.fingerprint);
  assert.equal(fingerprintOfPublicKey(key.publicLine.split(" ")[1]), key.fingerprint);
  assert.throws(() => fingerprintOfPublicKey("not a key"), /not a public key/);
});
