/**
 * Botlink tests — offline, localhost only. Proves the whole lane end to end
 * with keys generated by our own pure-TS keygen (if the OpenSSH container or
 * blob encoding is malformed, ssh2's parseKey rejects it HERE, not in
 * production): key parseability, status/inject roundtrips, and every
 * refusal path (wrong key, wrong user, unknown verb, bad payload, host-key
 * mismatch, oversize text).
 *
 * Usage: node --test tests/botlink.test.mjs   (build first: npm run build)
 */

import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import ssh2 from "ssh2";
const { Client, utils } = ssh2;
import { generateBotKey, fingerprintOfPublicKey, startBotlinkServer, botlinkRequest, verifyInjectLog, appendInjectEvent, renderInjectReport } from "../dist/botlink.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

function tmpDir() {
  return fs.mkdtempSync(path.join(os.tmpdir(), "botlink-test-"));
}

/** Server bound to an ephemeral localhost port + a legit client identity. */
async function makeServer(t, extra = {}) {
  const dir = tmpDir();
  const host = generateBotKey("test-host");
  const clientBot = generateBotKey("client-bot");
  const spool = path.join(dir, "spool");
  const srv = startBotlinkServer({
    listen: { host: "127.0.0.1", port: 0 },
    hostKeyPem: host.privatePem,
    authorizedPublicKeys: [clientBot.publicLine],
    spoolDir: spool,
    botName: "test-machine",
    ...extra,
  });
  await srv.listening;
  t.after(() => srv.close());
  return { srv, host, clientBot, spool };
}

test("keygen: ssh2 parses our keys, private matches its own public line", () => {
  const key = generateBotKey("roundtrip");
  assert.match(key.fingerprint, /^SHA256:[A-Za-z0-9+/]{43}$/);
  assert.ok(key.publicLine.startsWith("ssh-ed25519 "), "public line format");
  assert.ok(key.privatePem.includes("BEGIN OPENSSH PRIVATE KEY"));
  // ssh2 must accept both halves — this is the wire-format proof.
  const parsed = utils.parseKey(key.privatePem);
  assert.ok(parsed, "ssh2 parses our generated private key");
  assert.equal(
    Buffer.from(parsed.getPublicSSH()).toString("base64"),
    key.publicLine.split(" ")[1],
    "private key matches its own public line",
  );
  const parsedPub = utils.parseKey(key.publicLine);
  assert.ok(parsedPub, "ssh2 parses the public line too");
  assert.equal(
    Buffer.from(parsedPub.getPublicSSH()).toString("base64"),
    key.publicLine.split(" ")[1],
  );
});

test("keygen self-verify: EVERY emitted pair is parseable (ssh2 intermittently emits malformed containers)", () => {
  // Upstream bug, measured at ~0.4% (8/2000): generateKeyPairSync("ed25519")
  // occasionally drops a length prefix in the private section — ssh2's parser
  // and ssh-keygen both reject the file. generateBotKey self-verifies and
  // regenerates, so this loop must NEVER see an unparseable key; a failure
  // here means the retry guard itself broke.
  for (let i = 0; i < 300; i++) {
    const key = generateBotKey(`loop-${i}`);
    const priv = utils.parseKey(key.privatePem);
    assert.ok(priv, `iteration ${i}: private PEM must parse`);
    assert.equal(
      Buffer.from(priv.getPublicSSH()).toString("base64"),
      key.publicLine.split(" ")[1],
      `iteration ${i}: private must match its own public line`,
    );
  }
});

test("status/inject roundtrip over localhost", async (t) => {
  const { srv, host, clientBot, spool } = await makeServer(t, { botName: "roundtrip-machine" });
  const peer = {
    host: "127.0.0.1",
    port: srv.port,
    privateKeyPem: clientBot.privatePem,
    expectedHostKey: host.fingerprint,
  };
  const status = JSON.parse(await botlinkRequest(peer, "status"));
  assert.equal(status.ok, true);
  assert.equal(status.bot, "roundtrip-machine");
  assert.equal(status.spool_pending, 0);

  const ack = JSON.parse(
    await botlinkRequest(peer, "inject", {
      source: "client-bot",
      target: "orchestrator",
      text: "health ping from the test suite",
      thread: "shim",
    }),
  );
  assert.ok(ack.ok && ack.id, "inject acked");
  const files = fs.readdirSync(spool).filter((f) => f.endsWith(".inject.json"));
  assert.equal(files.length, 1, "exactly one spool file");
  const saved = JSON.parse(fs.readFileSync(path.join(spool, files[0]), "utf8"));
  assert.equal(saved.source, "client-bot");
  assert.equal(saved.target, "orchestrator");
  assert.equal(saved.text, "health ping from the test suite");
  assert.equal(saved.thread, "shim");
  // Provenance fields: WHICH key authenticated, from WHERE — independent of
  // the sender's self-reported `source`.
  assert.equal(saved.authenticated_key_fp, clientBot.fingerprint, "receiver recorded the authenticating key");
  assert.equal(saved.peer_ip, "127.0.0.1", "receiver recorded the peer address");
  // Audit log: one "received" entry, hash chain intact.
  const log1 = verifyInjectLog(spool);
  assert.equal(log1.length, 1);
  assert.equal(log1[0].event, "received");
  assert.equal(log1[0].id, ack.id);

  const status2 = JSON.parse(await botlinkRequest(peer, "status"));
  assert.equal(status2.injects_total, 1);
  assert.equal(status2.spool_pending, 1);
});

test("wrong client key is refused", async (t) => {
  const { srv, host } = await makeServer(t);
  const imposter = generateBotKey("imposter");
  await assert.rejects(
    botlinkRequest(
      { host: "127.0.0.1", port: srv.port, privateKeyPem: imposter.privatePem, expectedHostKey: host.fingerprint },
      "status",
    ),
    /unreachable|configured authentication|authentication|closed/i,
    "imposter key must not authenticate",
  );
});

test("host-key mismatch is refused (no TOFU)", async (t) => {
  const { srv, clientBot } = await makeServer(t);
  const wrongPin = generateBotKey("not-the-host").fingerprint;
  await assert.rejects(
    botlinkRequest(
      { host: "127.0.0.1", port: srv.port, privateKeyPem: clientBot.privatePem, expectedHostKey: wrongPin },
      "status",
    ),
    /unreachable|Could not connect|handshake|timed? ?out|Bad host key/i,
    "pinned fingerprint mismatch must fail the connection",
  );
});

test("unknown verb and malformed payloads are refused; nothing spools", async (t) => {
  const { srv, host, clientBot, spool } = await makeServer(t);
  const peer = {
    host: "127.0.0.1",
    port: srv.port,
    privateKeyPem: clientBot.privatePem,
    expectedHostKey: host.fingerprint,
  };

  // Raw exec of a forbidden verb through the same transport — the tool layer
  // only ever offers status/inject, so this simulates a hostile peer.
  const forbidden = await new Promise((resolve) => {
    const conn = new Client();
    conn
      .on("ready", () => {
        conn.exec("cat /etc/shadow", (err, stream) => {
          if (err) {
            conn.end();
            return resolve("rejected");
          }
          stream.on("close", (code) => {
            conn.end();
            resolve("ran-exit-" + code);
          });
          stream.end();
        });
      })
      .on("error", () => {
        conn.end();
        resolve("conn-error");
      })
      .connect({
        host: "127.0.0.1",
        port: srv.port,
        username: "clanker",
        privateKey: clientBot.privatePem,
        hostVerifier: (key) => key.toString("base64") === host.publicLine.split(" ")[1],
      });
  });
  assert.notEqual(forbidden, "ran-exit-0", "arbitrary commands must not run");
  assert.equal(fs.readdirSync(spool).filter((f) => f.endsWith(".inject.json")).length, 0, "nothing spooled by refusal");

  // Port forwarding must be refused — the lane is verbs-only, not a tunnel.
  const fwd = await new Promise((resolve) => {
    const conn = new Client();
    conn
      .on("ready", () => {
        conn.forwardOut("127.0.0.1", 0, "127.0.0.1", 22, (err, stream) => {
          conn.end();
          if (err) return resolve("refused");
          stream.close();
          return resolve("forwarded");
        });
      })
      .on("error", () => {
        conn.end();
        resolve("refused");
      })
      .connect({
        host: "127.0.0.1",
        port: srv.port,
        username: "clanker",
        privateKey: clientBot.privatePem,
        hostVerifier: (key) => key.toString("base64") === host.publicLine.split(" ")[1],
      });
  });
  assert.equal(fwd, "refused", "direct-tcpip forwarding must not be honored");

  // Oversized text.
  await assert.rejects(
    botlinkRequest(peer, "inject", { source: "c", target: "x", text: "x".repeat(4001) }),
    /invalid payload/i,
  );
  // Missing target.
  await assert.rejects(botlinkRequest(peer, "inject", { source: "c", text: "hi" }), /invalid payload/i);
  assert.equal(fs.readdirSync(spool).filter((f) => f.endsWith(".inject.json")).length, 0, "still nothing spooled");
});

test("inject audit log is tamper-evident: edits and deletions are caught", async (t) => {
  const { srv, host, clientBot, spool } = await makeServer(t);
  const peer = {
    host: "127.0.0.1",
    port: srv.port,
    privateKeyPem: clientBot.privatePem,
    expectedHostKey: host.fingerprint,
  };
  await botlinkRequest(peer, "inject", { source: "a", target: "b", text: "one" });
  await botlinkRequest(peer, "inject", { source: "c", target: "d", text: "two" });
  assert.equal(verifyInjectLog(spool).length, 2, "both received entries chain cleanly");

  // Tamper with an entry's text field → chain verify must fail.
  const logPath = path.join(spool, "inject.log");
  const lines = fs.readFileSync(logPath, "utf8").split("\n").filter(Boolean);
  const doctored = JSON.parse(lines[0]);
  doctored.detail = "innocent entry, honest";
  lines[0] = JSON.stringify(doctored);
  fs.writeFileSync(logPath, lines.join("\n") + "\n");
  assert.throws(() => verifyInjectLog(spool), /chain broken/, "edited entry detected");

  // Delete the FIRST entry → second entry's prev link no longer matches genesis.
  const lines2 = fs.readFileSync(logPath, "utf8").split("\n").filter(Boolean);
  fs.writeFileSync(logPath, lines2.slice(1).join("\n") + "\n");
  assert.throws(() => verifyInjectLog(spool), /chain/, "removed entry detected");
});

test("concurrent injects serialize into an intact chain (interleaved-writer race)", async (t) => {
  const { srv, host, clientBot, spool } = await makeServer(t);
  const peer = {
    host: "127.0.0.1",
    port: srv.port,
    privateKeyPem: clientBot.privatePem,
    expectedHostKey: host.fingerprint,
  };
  const N = 8;
  await Promise.all(
    Array.from({ length: N }, (_, i) =>
      botlinkRequest(peer, "inject", { source: `s${i}`, target: `t${i}`, text: `burst ${i}` }).catch((e) => {
        throw new Error(`inject ${i} failed: ${e.message}`);
      }),
    ),
  );
  const entries = verifyInjectLog(spool); // throws if the chain interleaved/broke
  assert.equal(entries.length, N, `all ${N} received entries present, chain verifies`);
  const ids = new Set(entries.map((e) => e.id));
  assert.equal(ids.size, N, "no duplicate ids");
});

test("structured task payloads roundtrip; junk task fields are refused", async (t) => {
  const { srv, host, clientBot, spool } = await makeServer(t);
  const peer = {
    host: "127.0.0.1",
    port: srv.port,
    privateKeyPem: clientBot.privatePem,
    expectedHostKey: host.fingerprint,
  };
  const ack = JSON.parse(
    await botlinkRequest(peer, "inject", {
      source: "client-bot",
      target: "shim",
      text: "review the re-vendor branch",
      thread: "shim",
      task: {
        kind: "review",
        repo: "shim",
        branch: "main",
        commit: "58833e6",
        acceptance: ["drift gate clean", "host_tests 570/570"],
        reply_to: "1790904000000-abc123",
        correlation: "round-7",
      },
      supersedes: "1790903000000-old456",
    }),
  );
  assert.ok(ack.ok);
  const files = fs.readdirSync(spool).filter((f) => f.endsWith(".inject.json"));
  const saved = JSON.parse(fs.readFileSync(path.join(spool, files[0]), "utf8"));
  assert.equal(saved.task.kind, "review");
  assert.equal(saved.task.commit, "58833e6");
  assert.deepEqual(saved.task.acceptance, ["drift gate clean", "host_tests 570/570"]);
  assert.equal(saved.task.reply_to, "1790904000000-abc123");
  // lineage fields survive zod — reserved so peers can adopt them without a
  // breaking schema change (unknown keys would otherwise be silently stripped)
  assert.equal(saved.task.correlation, "round-7");
  assert.equal(saved.supersedes, "1790903000000-old456");
  // audit detail carries kind + reply_to + lineage for metrics derivation
  const log = verifyInjectLog(spool);
  assert.match(log[0].detail ?? "", /kind=review/);
  assert.match(log[0].detail ?? "", /reply_to=1790904000000-abc123/);
  assert.match(log[0].detail ?? "", /supersedes=1790903000000-old456/);
  assert.match(log[0].detail ?? "", /correlation=round-7/);

  // junk kind / oversize acceptance / unknown field → refused, nothing spooled
  await assert.rejects(
    botlinkRequest(peer, "inject", { source: "c", target: "x", text: "hi", task: { kind: "destroy" } }),
    /invalid payload/i,
  );
  await assert.rejects(
    botlinkRequest(peer, "inject", {
      source: "c", target: "x", text: "hi",
      task: { kind: "review", acceptance: ["x".repeat(401)] },
    }),
    /invalid payload/i,
  );
  assert.equal(fs.readdirSync(spool).filter((f) => f.endsWith(".inject.json")).length, 1, "only the valid inject spooled");
});

test("report: metrics derive from the audit log (latency, completed, rework)", async (t) => {
  const { srv, host, clientBot, spool } = await makeServer(t);
  const peer = {
    host: "127.0.0.1",
    port: srv.port,
    privateKeyPem: clientBot.privatePem,
    expectedHostKey: host.fingerprint,
  };
  const first = JSON.parse(
    await botlinkRequest(peer, "inject", { source: "a", target: "shim", text: "one", task: { kind: "implement", reply_to: "R1" } }),
  );
  await new Promise((r) => setTimeout(r, 50));
  const second = JSON.parse(
    await botlinkRequest(peer, "inject", { source: "a", target: "shim", text: "two", task: { kind: "review", reply_to: "R1" } }),
  );
  // receiver-side lifecycle event on the first
  await appendInjectEvent(spool, { event: "completed", id: first.id, source: "a", target: "shim", detail: "merged @ aaa5592" });
  await appendInjectEvent(spool, { event: "consumed", id: first.id, source: "a", target: "shim" });
  const report = renderInjectReport(spool);
  assert.match(report, /2 inject\(s\), chain verified/);
  assert.match(report, /completed lifecycle events: 1/);
  assert.match(report, /merged @ aaa5592/);
  assert.match(report, /rework rounds \(shared reply_to\): 1/);
  assert.match(report, /received→consumed latency: \d+ms median \(1 paired\)/);
  assert.ok(second.ok);
});

test("append queue survives a failed append — audit trail never freezes (their reviewer's catch)", async (t) => {
  const { spool } = await makeServer(t);
  const logPath = path.join(spool, "inject.log");
  fs.writeFileSync(logPath, ""); // genesis — exists, so only the APPEND can fail
  // Make the append fail once: read-only log (deterministic EACCES as non-root
  // — same class as their reviewer's EBUSY/ENOSPC on Windows AV locks).
  fs.chmodSync(logPath, 0o444);
  t.after(() => fs.chmodSync(logPath, 0o644));
  const first = await appendInjectEvent(spool, { event: "received", id: "a1", source: "s", target: "t" }).then(
    () => "ok",
    () => "failed",
  );
  assert.equal(first, "failed", "first append hits the read-only log");
  fs.chmodSync(logPath, 0o644);
  const second = await appendInjectEvent(spool, { event: "received", id: "a2", source: "s", target: "t" }).then(
    () => "ok",
    () => "failed",
  );
  assert.equal(second, "ok", "queue recovered — the failure did not poison later appends");
  const entries = verifyInjectLog(spool);
  assert.equal(entries.length, 1, "only the recovered entry landed");
  assert.equal(entries[0].id, "a2");
});

test("report reconciles archive files against the log — a lost append is visible", async (t) => {
  const { srv, host, clientBot, spool } = await makeServer(t);
  const peer = {
    host: "127.0.0.1",
    port: srv.port,
    privateKeyPem: clientBot.privatePem,
    expectedHostKey: host.fingerprint,
  };
  // One clean inject (file + received event + consumed + archive move).
  const ack = JSON.parse(
    await botlinkRequest(peer, "inject", { source: "a", target: "shim", text: "logged one", task: { kind: "status" } }),
  );
  assert.ok(ack.ok);
  await new Promise((r) => setTimeout(r, 150));
  fs.mkdirSync(path.join(spool, "archive"), { recursive: true });
  fs.renameSync(
    path.join(spool, `${ack.id}.inject.json`),
    path.join(spool, "archive", `${ack.id}.inject.json`),
  );
  // Now forge the failure signature: a file lands in archive whose received
  // entry never made the log (simulates append-loss AFTER the spool write).
  fs.writeFileSync(path.join(spool, "archive", "9999000000-dead00.inject.json"), '{"id":"9999000000-dead00"}');
  const report = renderInjectReport(spool);
  assert.match(report, /unlogged inject files \(audit append lost\): 1/);
  assert.match(report, /9999000000-dead00/);
  // and the clean case shows no false positive for the logged one
  assert.doesNotMatch(report, new RegExp(`unlogged[^\n]*${ack.id}`));
});

test("tail truncation is caught by the head artifact; legacy headless logs still verify", async (t) => {
  const { spool } = await makeServer(t);
  const logPath = path.join(spool, "inject.log");
  await appendInjectEvent(spool, { event: "received", id: "t1", source: "s", target: "t" });
  await appendInjectEvent(spool, { event: "consumed", id: "t1", source: "s", target: "t" });
  assert.equal(verifyInjectLog(spool).length, 2, "both entries chain-verify");

  // Delete the NEWEST line: replay alone sees a valid shorter chain — the
  // persisted head hash is what catches it (their reviewer's part-2 catch).
  const lines = fs.readFileSync(logPath, "utf8").split("\n").filter(Boolean);
  fs.writeFileSync(logPath, lines.slice(0, -1).join("\n") + "\n");
  assert.throws(() => verifyInjectLog(spool), /tail truncated/, "newest-entry deletion detected");

  // Legacy log with no .head artifact: replay verdict stands (can't tell
  // "never written" from "deleted" — fail-open on the artifact, never invent).
  fs.rmSync(path.join(spool, "inject.log.head"));
  assert.equal(verifyInjectLog(spool).length, 1, "legacy headless log still verifies");
});

test("log entries carry structured lineage meta; rework derives from the field, not detail text", async (t) => {
  const { srv, host, clientBot, spool } = await makeServer(t);
  const peer = {
    host: "127.0.0.1",
    port: srv.port,
    privateKeyPem: clientBot.privatePem,
    expectedHostKey: host.fingerprint,
  };
  await botlinkRequest(peer, "inject", { source: "a", target: "shim", text: "one", task: { kind: "implement", reply_to: "R9" } });
  await botlinkRequest(peer, "inject", { source: "a", target: "shim", text: "two", task: { kind: "review", reply_to: "R9" } });
  const entries = verifyInjectLog(spool);
  const withMeta = entries.filter((e) => e.meta?.reply_to === "R9");
  assert.equal(withMeta.length, 2, "both received entries carry meta.reply_to (hash-covered)");
  // even with detail text gone, rework still derives — no format-drift zeroing
  const report = renderInjectReport(spool);
  assert.match(report, /rework rounds \(shared reply_to\): 1/);
});

test("fingerprintOfPublicKey accepts blobs and lines; rejects junk", () => {
  const key = generateBotKey("fp");
  assert.equal(fingerprintOfPublicKey(key.publicLine), key.fingerprint);
  assert.equal(fingerprintOfPublicKey(key.publicLine.split(" ")[1]), key.fingerprint);
  assert.throws(() => fingerprintOfPublicKey("not a key"), /not a public key/);
});
